erp-java/src/main/java/modelo/Usuario.java
Criação da classe Usuario com atributos nome, login e senha e seus respectivos getters e setters.
=> Criação da classe Usuario.java

.gitignore, erp-java/src/main/java/dao/FornecedorDAO.java
Método criado, aguardando análise.
=> Primeiro modelo de alterarStatus

erp-java/src/main/java/modelo/Entrada.java
Retirando os métodos não necessários
=> Atualizando entrada

erp-java/src/main/java/dao/ProdutoDAO.java
Cria o método alterarStatus na classe ProdutoDAO, que recebe um produto e gera um retorno do tipo booleano.
=> Criação do método alterarStatus

erp-java/src/main/java/modelo/Produto.java
=> Update Classe produto

erp-java/src/test/java/dao/EntradaDAOTest.java
Criação do teste alterarStatus(Entrada), ainda retornando false no momento.
=> Criação do teste alterarStatus(Entrada)

erp-java/pom.xml, erp-java/src/test/java/dao/EntradaDAOTest.java
- instancia 1 fornecedor, 1 serviço e 1 entrada e as salva, após isso ele salva as instancias criadas, e usa o método buscar pra verificar se foi salvo. obs. add dependencia para mockito
Este teste necessita da criação de um método chamado **getProduto();** na classe Entrada, para instanciar uma entrada, é preciso passar uma instancia de produto.
=> feat: cria o test para avaliar o metodo Buscar da classe EntradaDAO

erp-java/src/test/java/dao/FornecedorDAOTest.java
Implementado o teste de salvar fornecedor, bem como criação construtor da classe fornecedor.
=> Teste de salvar fornecedor

erp-java/src/main/java/modelo/Fornecedor.java
Vazio (necessário em alguns métodos do FornecedorDAO), com todos os parâmetros e todos, exceto ID.
=> Definidos os construtores 

.gitignore, erp-java/src/test/java/dao/FornecedorDAOTest.java
Desenvolvimento de uma classe teste verificando método buscar(nome, status).
=> Teste Método buscar(nome,status)

erp-java/pom.xml, erp-java/src/test/java/dao/ProdutoDAOTest.java
Importação do mockito para o projeto
=> Testes para salvarProduto(Mercadoria e Servico)

erp-java/src/main/java/dao/FornecedorDAO.java
conversão da verificação de STATUS booleano para um numero inteiro.
=> Correção do Parâmetro STATUS

erp-java/src/main/java/modelo/Fornecedor.java, erp-java/src/test/java/dao/FornecedorDAOTest.java
Criação do test metodo buscar por Cnpj e status
=> Criação do test metodo buscar por Cnpj e status

erp-java/src/test/java/FornecedorDAOTest.java
Criação de Test metodo BuscarIDeStatus
=> Criação de Test metodo BuscarIDeStatus

erp-java/src/main/java/view/BuscaEntrada.java, erp-java/src/main/java/view/CadrastoEntrada.java, erp-java/src/main/java/view/EditarEntrada.java, erp-java/src/main/java/view/Menu.java
Retirar Main EditarEntrada BuscarEntrada e CadastroEntrada
=> Retirar main

erp-java/src/main/java/view/EditarEntrada.java
Adiciona caixa de dialogo para confirmação de cancelamento
=> BtnCancelarEntrada

erp-java/src/main/java/controlador/SaidaController.java, erp-java/src/main/java/view/BuscarSaida.form, erp-java/src/main/java/view/BuscarSaida.java
Criado método preencherLista para preencher a lista de saídas.
O método necessita da criação de um método buscarTodas() no SaidaDAO.
=> Criado método preencherLista

erp-java/src/main/java/view/BuscarSaida.java
Criada ação para abrir a tela de registro ao clicar no botão de Registro.
=> Abrir a tela de registro

erp-java/src/main/java/view/RegistrarSaida.java
Fecha a tela de Registro de Saida.
=> Fechar RegistroSaida

erp-java/src/main/java/view/RegistrarSaida.form, erp-java/src/main/java/view/RegistrarSaida.java
Abre uma tela informando se foi possível salvar a saida, ou se teve erro.
=> Aviso de Confirmação ou Erro

erp-java/src/main/java/controlador/SaidaController.java, erp-java/src/main/java/modelo/Saida.java, erp-java/src/main/java/view/RegistrarSaida.java
=> Criação SaidaController

erp-java/src/main/java/controlador/FornecedorController.java, erp-java/src/main/java/dao/FornecedorDAO.java, erp-java/src/main/java/view/BuscarFornecedor.form, erp-java/src/main/java/view/BuscarFornecedor.java, erp-java/src/main/java/view/EditarFornecedor.form, erp-java/src/main/java/view/EditarFornecedor.java
=> Fornecedor: Botão Editar
